Repository transferwise/neptune-web, pull requests merged in 2020-11, with the labels that each got.

#633 docs: RFC for i18n of components
  rfc/0004-i18n.md
Labels: RFC

#498 feat: add Tile and Decision components
  bundlesize.config.json
  packages/components/package.json
  packages/components/src/common/Option/Option.js
  packages/components/src/common/index.js
  packages/components/src/common/key.js
  packages/components/src/common/keyCodes.js
  packages/components/src/decision/Decision.js
  packages/components/src/decision/Decision.less
  packages/components/src/decision/Decision.spec.js
  packages/components/src/decision/Decision.story.js
  packages/components/src/decision/index.js
  packages/components/src/index.js
  packages/components/src/lab/field/Field.story.js
  packages/components/src/navigationOption/NavigationOption.js
  packages/components/src/nudge/Nudge.story.js
  packages/components/src/sizeSwapper/SizeSwapper.js
  packages/components/src/sizeSwapper/SizeSwapper.spec.js
  packages/components/src/sizeSwapper/SizeSwapper.story.js
  packages/components/src/sizeSwapper/hooks/index.js
  packages/components/src/sizeSwapper/hooks/useClientWidth.js
  packages/components/src/sizeSwapper/hooks/useClientWidth.spec.js
  packages/components/src/sizeSwapper/index.js
  packages/components/src/ssr.spec.js
  packages/components/src/tile/Tile.js
  packages/components/src/tile/Tile.less
  packages/components/src/tile/Tile.spec.js
  packages/components/src/tile/Tile.story.js
  packages/components/src/tile/__snapshots__/Tile.spec.js.snap
  packages/components/src/tile/index.js
  packages/css/src/less/addons/_display-utilities.less
  packages/css/src/less/decision.less
  packages/docs/liveEditorCode/decision.code.js
  packages/docs/liveEditorCode/tile.code.js
  packages/docs/pages/components/navigation/Decision.mdx
  packages/docs/utils/generatePropsTable/GeneratePropsTable.js
Labels: neptune

#650 refactor: summary api alignment
  packages/components/package.json
  packages/components/src/common/propsValues/status.js
  packages/components/src/moneyInput/MoneyInput.less
  packages/components/src/ssr.spec.js
  packages/components/src/summary/Summary.js
  packages/components/src/summary/Summary.less
  packages/components/src/summary/Summary.spec.js
  packages/components/src/summary/Summary.story.js
  packages/components/src/summary/__snapshots__/Summary.spec.js.snap
  packages/components/src/summary/info/Info.js
  packages/components/src/summary/info/Info.less
  packages/components/src/summary/info/Info.spec.js
  packages/components/src/summary/info/Info.story.js
  packages/components/src/summary/info/index.js
  packages/components/src/utilities/deprecatedProp/deprecatedProp.js
  packages/components/src/utilities/deprecatedProp/deprecatedProp.spec.js
  packages/components/src/utilities/deprecatedProp/index.js
  packages/components/src/utilities/index.js
  packages/docs/liveEditorCode/summary.code.js
  packages/docs/package.json
  packages/docs/pages/components/content/Summary.mdx
  packages/dynamic-flows/package.json
  yarn.lock
Labels: neptune

#671 feat: adds the ability to provide an icon and use markdown inside an alert
  bundlesize.config.json
  packages/components/.storybook/config.js
  packages/components/package.json
  packages/components/src/alert/Alert.js
  packages/components/src/alert/Alert.spec.js
  packages/components/src/alert/Alert.story.js
  packages/components/src/alert/closeButton/CloseButton.js
  packages/components/src/alert/closeButton/CloseButton.less
  packages/components/src/alert/closeButton/index.js
  packages/components/src/alert/inlineMarkdown/InlineMarkdown.js
  packages/components/src/alert/inlineMarkdown/index.js
  packages/components/src/alert/withArrow/index.js
  packages/components/src/alert/withArrow/withArrow.js
  packages/components/src/alert/withArrow/withArrow.spec.js
  packages/components/src/common/index.js
  packages/components/src/common/markdownNodeTypes.js
  packages/components/src/common/propsValues/messageType.js
  packages/components/src/common/propsValues/position.js
  packages/components/src/common/propsValues/sentiment.js
  packages/components/src/index.js
  packages/components/src/inlineAlert/InlineAlert.js
  packages/components/src/inlineAlert/InlineAlert.spec.js
  packages/components/src/inlineAlert/InlineAlert.story.js
  packages/components/src/inlineAlert/index.js
  packages/components/src/lab/field/Field.js
  packages/components/src/lab/field/Field.story.js
  packages/components/src/markdown/Markdown.js
  packages/components/src/markdown/Markdown.spec.js
  packages/components/src/markdown/Markdown.story.js
  packages/components/src/ssr.spec.js
  packages/components/src/tabs/Tabs.story.js
  packages/components/src/typeahead/Typeahead.js
  packages/components/src/typeahead/Typeahead.spec.js
  packages/components/src/typeahead/Typeahead.story.js
  packages/components/src/utilities/deprecatedProp/deprecatedProp.js
  packages/components/src/utilities/deprecatedProp/deprecatedProp.spec.js
  packages/components/src/utilities/logActionRequired.js
  packages/components/test/neptuneCssTest/NeptuneCssTest.story.js
  packages/components/test/neptuneCssTest/components/alerts.html
  packages/css/package.json
  packages/css/src/less/alerts.less
  packages/css/src/less/core/_scaffolding.less
  packages/css/src/less/mixins/_alerts.less
  packages/css/src/less/mixins/_flex.less
  packages/docs/liveEditorCode/alert.code.js
  packages/docs/liveEditorCode/tabs.code.js
  packages/docs/pages/components/alerts/Alert.mdx
  packages/docs/pages/lab/Pagination.mdx
  packages/dynamic-flows/src/field/Field.js
  packages/dynamic-flows/src/field/Field.spec.js
  packages/dynamic-flows/src/jsonSchemaForm/JsonSchemaForm.e2e.spec.js
  packages/dynamic-flows/src/jsonSchemaForm/controlFeedback/ControlFeedback.js
  packages/dynamic-flows/src/jsonSchemaForm/controlFeedback/ControlFeedback.spec.js
  packages/dynamic-flows/src/layout/DynamicLayout.e2e.spec.js
  packages/dynamic-flows/src/layout/alert/index.js
  packages/dynamic-flows/src/layout/alert/spec.js
  yarn.lock
Labels: dynamic-flows, neptune

#638 chore: integrate visual-regression in CI
  .circleci/config.yml
  .gitignore
  package.json
  packages/components/.storybook/config.js
  packages/components/package.json
  yarn.lock
Labels: maintenance, neptune
